#!/usr/bin/env bash
# R2 gate B: is the PGRN converter portable *and* platform-neutral in its output?
#
# Two claims, because passing the suite on Linux would not by itself prove the
# same bytes come out:
#
#   1. the Linux build passes the whole converter suite — byte-parity against the
#      Python reference implementation, resume, cancellation semantics;
#   2. macOS and Linux, given the identical source GGUF, emit PGRN files with the
#      identical SHA-256, so a model converted on one platform is usable on the
#      other without reconversion.
#
# Claim 2 is the interesting one: the macOS build hashes with CommonCrypto and the
# Linux build with the portable fallback. Same digest means that substitution is
# genuinely invisible in the output.
#
# Usage: bench/m2/run_converter_gate.sh
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

MAC_BIN="$ENGINE_DIR/build-static/bin/llama-pgrn-convert"
SHARED="$(mktemp -d /tmp/slip-m2-conv-XXXXXX)"
trap 'rm -rf "$SHARED"' EXIT

if [ ! -x "$MAC_BIN" ]; then
    echo "missing macOS converter: $MAC_BIN" >&2
    echo "build it with: cmake --build vendor/llama.cpp/build-static --target llama-pgrn-convert" >&2
    exit 1
fi
require_docker
build_image
export_engine_tree "$SHARED/engine.tar"

# One synthetic GGUF feeds both platforms, generated by the test helper so the
# fixture cannot drift away from what the suite exercises.
say "generate the shared source GGUF"
PYTHONPATH="$REPO_ROOT" python3 - "$SHARED/model.gguf" <<'PY'
import sys
from pathlib import Path
from tests.m1.test_pgrn_convert_native_parity import build_synthetic_gguf
meta = build_synthetic_gguf(Path(sys.argv[1]), n_layers=8, n_experts=24, seed=1789)
print(f"{meta['n_layers']} layers x {meta['n_experts']} experts, "
      f"{Path(sys.argv[1]).stat().st_size} bytes")
PY

say "convert on macOS (CommonCrypto SHA path)"
"$MAC_BIN" --input "$SHARED/model.gguf" --output "$SHARED/mac.pgrn" --min-free-gb 0 >/dev/null
SHA_MAC=$(shasum -a 256 "$SHARED/mac.pgrn" | cut -d' ' -f1)
echo "macOS  PGRN: $SHA_MAC"

say "build on Linux, run the suite, convert the same GGUF"
docker run --rm \
    -v "$REPO_ROOT:/repo:ro" \
    -v "$SHARED:/shared" \
    -w /work "$IMAGE" bash -lc '
set -e
mkdir -p src && tar xf /shared/engine.tar -C src
cd src
cmake -B build '"$CMAKE_FLAGS"' -DLLAMA_BUILD_TESTS=OFF > /tmp/cfg.log 2>&1 || {
    echo "--- configure failed ---"; tail -40 /tmp/cfg.log; exit 1; }
cmake --build build --target llama-pgrn-convert -j "$(nproc)" > /tmp/build.log 2>&1 || {
    echo "--- build failed ---"
    grep -E "error:" /tmp/build.log | sed -E "s|/work/src/||" | sort -u | head -30
    exit 1; }
echo "linux converter built"

export PGRN_CONVERT_BIN=/work/src/build/bin/llama-pgrn-convert
export PYTHONPATH=/repo
cd /tmp   # keep the read-only /repo free of __pycache__
python3 -m unittest \
    tests.m1.test_pgrn_convert_native_parity \
    tests.m1.test_pgrn_convert_resume 2>&1 | tail -6

"$PGRN_CONVERT_BIN" --input /shared/model.gguf --output /shared/linux.pgrn --min-free-gb 0 >/dev/null
'

SHA_LINUX=$(shasum -a 256 "$SHARED/linux.pgrn" | cut -d' ' -f1)
echo "Linux  PGRN: $SHA_LINUX"

say "verdict"
if [ "$SHA_MAC" = "$SHA_LINUX" ]; then
    echo "PASS — macOS and Linux emit byte-identical PGRN ($SHA_MAC)"
else
    echo "FAIL — digests differ"
    echo "  macOS: $SHA_MAC"
    echo "  Linux: $SHA_LINUX"
    exit 1
fi
